POST https://kgdg3a4p0m.execute-api.us-west-2.amazonaws.com/test/keys/triggerExpiration
Content-Type: application/json

{
    "message": "This is an amazing demo message from the CLOUD!",
    "simulateBounceToggle": false,
    "simulateComplaintToggle": false
}